### ISSUE TITLE
[Bug] kyverno-documentation seems incorrect re: wildcards

### ISSUE THREAD

**Issue by menzenski** [kyverno/kyverno-json#342]
### Kyverno JSON Version

0.1.0

### Description

I am on version `0.0.2`, which I can't select in the bug issue form version selector (I installed via Homebrew, and the only version available there is 0.0.2)

The [kyverno-json documentation](https://kyverno.github.io/kyverno-json/latest/policies/policies/#match-and-exclude) includes an example ValidatingPolicy that uses `validate` with a wildcard `?*`:

```yaml
apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: required-s3-tags
spec:
  rules:
    - name: require-team-tag
      identifier: address
      match:
        any:
        - type: aws_s3_bucket
      exclude:
        any:
        - name: bypass-me
      validate:
        assert:
          all:
          - values:
              tags:
                Team: ?*
``` 

However, this doesn't work. In the Kyverno [playground](https://kyverno.github.io/kyverno-json/latest/_playground/) an attempt to use this policy just returns `{"results": null}`.  On the command line there is an error thrown:

```shell
$ kyverno-json scan --payload my_payload.yaml --policy required_s3_tags.yaml
Loading policies ...
Error: failed to parse document (spec.rules[0].validate: Invalid value: value provided for unknown field)
```

### Steps to reproduce

1. Define policy with the YAML example from the documentation:

```shell
cat <<EOF > test_policy.yaml
apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: required-s3-tags
spec:
  rules:
    - name: require-team-tag
      identifier: address
      match:
        any:
        - type: aws_s3_bucket
      exclude:
        any:
        - name: bypass-me
      validate:
        assert:
          all:
          - values:
              tags:
                Team: ?*
EOF
```

2. Invoke `kyverno-json` using that policy:

```shell
$ kyverno-json scan --policy test_policy.yaml
```

This throws an error:

```shell
$ kyverno-json scan --policy test_policy.yaml
Loading policies ...
Error: failed to parse document (spec.rules[0].validate: Invalid value: value provided for unknown field)
```

### Expected behavior

I had expected that the examples provided in the documentation would work. 

### Troubleshooting

- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by menzenski** [comment]
Many of the examples on `https://kyverno.github.io/kyverno-json/latest/policies/asserts/#assert` also contain the `validate` property. These seem to exhibit the same error.

For example:

```yaml
apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: test
spec:
  rules:
    - name: foo-bar-4
      validate:
        assert:
          all:
          - message: "..."
            check:
              # project field `foo` onto itself, the content of `foo` becomes the current object for descendants
              foo:

                # evaluate expression `(bar > `3`)`, the boolean result becomes the current object for descendants
                # the `true` leaf is compared with the current value `true`
                (bar > `3`): true

                # evaluate expression `(!baz)`, the boolean result becomes the current object for descendants
                # the leaf `false` is compared with the current value `false`
                (!baz): false

                # evaluate expression `(bar + bat)`, the numeric result becomes the current object for descendants
                # the leaf `10` is compared with the current value `10`
                (bar + bat): 10
```

```shell
$ kyverno-json scan --policy test_policy_2.yaml
Loading policies ...
Error: failed to parse document (spec.rules[0].validate: Invalid value: value provided for unknown field)
```

**Comment by eddycharly** [comment]
Hmm, thanks for reporting !

Will check that next week.

**Comment by Curious-x** [comment]
Hi, I was building a project which used KyvernoJSON, as I was understanding it's working I stumbled upon the same mistakes which are mentioned above. I figured it out: it was mainly due to some mistakes in some of the examples on the website [Assertion Tree](https://kyverno.github.io/kyverno-json/latest/policies/asserts/#assert).

> The main issue: use of validate before assert and missing check after assert.

This is the example given on latest website:
![image](https://github.com/user-attachments/assets/a3d7f7b1-f5bc-419e-a558-7886ea477c9d)

and KyvernoJSON playground give this error:
```yaml
{
  "results": [
    {
      "policy": "test",
      "rule": "foo-bar",
      "result": "error",
      "message": "<nil>: Invalid value: \"null\": an empty assert is not valid"
    }
  ]
}
```


If corrected according to doc:

> An assert declaration contains an any or all list in which each entry contains a:
> check: the assertion check
> message: an optional message

The policy becomes:
```yaml

apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: test
spec:
  rules:
    - name: foo-bar
      assert:
          all:
          - check:
             foo:
              bar:
              - 1
              - 2
              - 3
```

and the result is as expected:

```yaml
{
  "results": [
    {
      "policy": "test",
      "rule": "foo-bar",
      "result": "pass",
      "message": ""
    }
  ]
}
```

**Comment by Curious-x** [comment]
The first [comment](https://github.com/kyverno/kyverno-json/issues/342#issue-2202297122) of @menzenski  in this thread refers to the wildcard.

Playground Example [Link](https://kyverno.github.io/kyverno-json/latest/_playground/?content=H4sIAAAAAAAAA22QsW4DIRBEf2VEYzuyHbmlSZEfcBG5umYFG5scB4jlHJ2i%2FHvgdI4VK1Tsm2F22S%2BVondmUlpRcifO4mLQ%2BJAY9v105Rzi3sXn64F8utChy13oXbAaJ%2FLOUnHhfJwDmjJwocpItwIINLBGYSmtlsRmEfLoWZY7sFuMn85bQ9mCQ8nTTQVIhHPRdzBD7x%2FIDgOL0LkmdeqYWTgYxuuFTY9R6py%2FDTr19yVgmks%2F0nbeY%2FyXY31LW69enlZbN9TOm039bh5ZbVWiyUeyda33hNmj8bYsBFDfPzG4LSZ%2FAQAA)

### To use wildcard:

One could use custom (wildcard function)[https://kyverno.github.io/kyverno-json/latest/jp/functions/#custom-functions] provided by Kyverno-json as at the time of this comment JMESPath don't support wildcards comparison, but it's proposed.
Policy
```yaml
apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: test
spec:
  rules:
    - name: wildcard entry
      assert:
          all:
          - message: "Presence Check using wildcard"
            check:
                foo:
                 (wildcard('?*',image)): true
```

Data
```yaml
foo:
  image: Test
```

Output
```yaml
{
  "results": [
    {
      "policy": "test",
      "rule": "wildcard entry",
      "result": "pass",
      "message": ""
    }
  ]
}
```
