### ISSUE TITLE
[Feature] Allow expression as keynames

### ISSUE THREAD

**Issue by vishal-chdhry** [kyverno/kyverno-json#86]
### Problem Statement

The following policy won't work when we use a variable as key, it can be quite helpful to have this ability
```yaml
apiVersion: json.kyverno.io/v1alpha1
kind: Policy
metadata:
  name: required-latest-platform-fargate
spec:
  rules:
    - name: required-latest-platform
      match:
        any:
        - type: aws_ecs_service
          values:
            launch_type: FARGATE
      context:
      - name: pv
        variable: platform_version
      validate:
        message: "ECS Fargate services should run on the latest Fargate platform version"
        assert:
          all:
          - (values.platform_version == 'LATEST'): true
          # - (values.($pv) == 'LATEST'): true # DOES NOT WORK
          # - values:
          #   ($pv): 'LATEST' # DOES NOT WORK
```

### Solution Description

Extend `at` custom function to have support for objects.

### Research

- [ ] I have searched other issues in this repository and mine is not recorded.
